//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeAcademyAttendanceSystemAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Students_Attendance
    {
        public int students_attendance_id { get; set; }
        public Nullable<System.DateTime> students_attendance_date { get; set; }
        public Nullable<bool> students_attendance_status { get; set; }
        public string students_attendance_sender_ip { get; set; }
        public Nullable<int> students_attendance_student_id { get; set; }
    
        public virtual Students Students { get; set; }
    }
}
