//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeAcademyAttendanceSystemAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class System_Settings
    {
        public int system_settings_id { get; set; }
        public string system_settings_academy_ip { get; set; }
        public Nullable<int> system_settings_qr_code_available_minute { get; set; }
    }
}
