//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeAcademyAttendanceSystemAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Teacher_Roles
    {
        public int teacher_roles_id { get; set; }
        public Nullable<int> teacher_roles_teacher_id { get; set; }
        public Nullable<int> teacher_roles_role_types_id { get; set; }
    
        public virtual Role_Types Role_Types { get; set; }
        public virtual Teachers Teachers { get; set; }
    }
}
